using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.CompilerServices;

namespace Journaltask{
    public class Journal{
        private List<Entry> _entries;
        private List<string> _prompts;

        public Journal(){
            _entries = new List<Entry>();
            
            _prompts = new List<string>{
                // these questions below was generated was generated by ai
                "Who was the most interesting person I interacted with today?",
                "What was the best part of my day?",
                "How did I see the hand of the Lord in my life today?",
                "What was the strongest emotion I felt today?",
                "If I had one thing I could do over today, what would it be?"
            };
        }
    
        public void AddEntry(string content){
            if (_prompts == null || _prompts.Count == 0){
                Console.WriteLine("Error cannot add prompt try again.");
                return;
            }

            Random random = new Random();
            String prompt = _prompts[random.Next(0, _prompts.Count)];
            String date = DateTime.Now.ToString();
            Entry newEntry = new Entry(date, prompt, content);
            Console.WriteLine($"This is the prompt {prompt}");
            _entries.Add(newEntry);
        }

        public void displayEntries(){
            foreach (Entry entry in _entries){
                Console.WriteLine(entry.ToString());
                Console.WriteLine("=============================================");
            }
        }
        public void SaveToFile(string filename){
            try{
                using (StreamWriter writer = new StreamWriter(filename)){
                    foreach (Entry entry in _entries)
                    {
                        writer.WriteLine($"{entry.Date}|{entry.Prompt}|{entry.Content}");

                    }
                    Console.WriteLine($"Journal Saved to {filename}");
                }
            }
            catch (Exception e){
                Console.WriteLine("Error saving the journal: " + e.Message);
            }

        }

        public void LoadFromFile(string filename){
            try{
                if (!File.Exists(filename)){
                    Console.WriteLine("File cannot be found please try again!");
                    return;
                }
                _entries.Clear(); 
                using(StreamReader reader = new StreamReader(filename)){
                    string line;
                    while ((line=reader.ReadLine()) != null){
                        string[] parts = line.Split('|');

                        if (parts.Length == 3){
                            Entry entry = new Entry(parts[0], parts[1], parts[2]);
                            _entries.Add(entry);
                        }
                    }
                }
                Console.WriteLine($"You got the journal from {filename}");
            }
            catch (Exception e){
                Console.WriteLine("Error loading the journal try again later: " + e.Message);
            }
        }
    }
}
